### ISSUE TITLE
GetSystemTimePreciseAsFileTime is the Windows 8 and Windows Server 2012 new API

### ISSUE THREAD

**Issue by milanmilas** [fedjabosnic/hotfix#50]
Exception on windows 7 as api from windows 8 and windows server 2012 is used.
GetSystemTimePreciseAsFileTime

**Comment by fedjabosnic** [comment]
@milanmilas There are try catches around the usage of that method - is this an exception or a compile error?

**Comment by milanmilas** [comment]
true, it will be catched in try catch.
